# These are all indexed from 0
festival.name=Worcester Beer, Cider and Perry Festival
data.start.line=7
drink.name.column=5
drink.description.column=13
drink.price.column=59
drink.abv.column=6
brewer.name.column=4
brewer.location.column=14
drink.feature.column=10
drink.type=beer
drink.quantity.remaining.column=-1
drink.feature.format=SeparateColumns
drink.feature.mild.column=24
drink.feature.dark.column=26
drink.feature.brown.column=28
drink.feature.golden.column=30
drink.feature.stout.column=32
drink.feature.lager.column=34
drink.feature.unusual.column=36
drink.feature.organic.column=38