# These are all indexed from 0
festival.name=Worcester Beer, Cider and Perry Festival
data.start.line=7
drink.name.column=F
drink.description.column=N
drink.price.column=BH
drink.abv.column=G
brewer.name.column=E
brewer.location.column=14
drink.type=beer
drink.quantity.remaining.column=-1
drink.feature.format=SeparateColumns
drink.feature.mild.column=Y
drink.feature.dark.column=AA
drink.feature.brown.column=AC
drink.feature.golden.column=AE
drink.feature.stout.column=AG
drink.feature.lager.column=AI
drink.feature.unusual.column=AK
drink.feature.organic.column=AM