# These are all indexed from 0
festival.name=Worcester Beer, Cider and Perry Festival
data.start.line=7
drink.name.column=F
drink.description.column=N
drink.price.column=BH
drink.abv.column=G
brewer.name.column=E
brewer.location.column=O
drink.type=beer
drink.quantity.remaining.column=BV
drink.feature.column=K
drink.feature.format=Mixed
drink.feature.Mild.column=Y
drink.feature.Dark.column=AA
drink.feature.Brown.column=AC
drink.feature.Golden.column=AE
drink.feature.Stout.column=AG
drink.feature.Lager.column=AI
drink.feature.Unusual.column=AK
drink.feature.Organic.column=AM